# Requires an API token action secret set called 'API_TOKEN_GITHUB'
name: Keep gh-pages up-to-date with main

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository

      - name: Update gh-pages branch to current main
        run: |
          git push origin -d ph-pages
          git checkout -b gh-pages
          git push origin gh-pages
