name: Keep gh-pages up-to-date with main

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository

      - name: Update gh-pages branch to current main
        run: |
          #git config --local user.email "github-actions[bot]@users.noreply.github.com"
          #git config --local user.name "github-actions[bot]"
          git remote set-url origin https://github-actions[bot]:${{ secrets.API_TOKEN_GITHUB }}@github.com/github-actions[bot]/project.git
          git push origin -d gh-pages
          git checkout -b gh-pages
          #git push origin gh-pages

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: ${{ github.head_ref }}
          force: true
